### PR TITLE
Fix joint_state_broadcaster performance issues

### LINKED ISSUE #1409: High CPU load due to joint state broadcaster
**Describe the bug**

I am currently looking into the issue why our ros2control node is consuming 100% cpu load. 
For testing purposes I disabled all loaded controllers one by one. As expected the cpu drops a bit for each controller. But for the joint state broadcaster this was rather extreme. I see a change in cpu load for node of ~15-20%. 
This is not the case for other controllers that publish messages at the same rate of 500Hz. 

We have a rather large amount of joints in our system: 34. 

**Expected behavior**

I would expect that such a simple controller shouldn't consume that much cpu power. 

**Environment (please complete the following information):**
 - OS:  ubuntu 24.04
 - Version Jazzy - 4.16.0

**Additional context**

When taking a look at the code I would guess at the moment three places that could result in a higher cpu load:

1. there are rather many operations on the `map_interface_to_joint_state_` -> but unordered_map should be fast enough
2. mutex operation in the RT publisher
3. Reading the values from the state interfaces -> Not sure if there is any synchronization happening ?

### PR DESCRIPTION
**Pull request by jordan-palacios**
This PR will include adding a new test for checking performance in a setup with lots of state interfaces (>500). I'll include here the results of each incremental performance fix commit added.

Since we have also noticed a lot of variance in the results, we'll run it a few times. All results will be summarized here.

Fixes #1409.

### CODE REVIEW

**Comment by jordan-palacios** [comment]
Performance of the current `master` version.

```
[INFO] [1744704812.699545539] [joint_state_broadcaster]: Average update time: 240.174700 us
[INFO] [1744704812.699598892] [joint_state_broadcaster]: Variance: 231730.945780 us
--
[INFO] [1744704815.285795981] [joint_state_broadcaster]: Average update time: 236.002800 us
[INFO] [1744704815.285851910] [joint_state_broadcaster]: Variance: 297345.111392 us
--
[INFO] [1744704817.849313397] [joint_state_broadcaster]: Average update time: 234.468100 us
[INFO] [1744704817.849375057] [joint_state_broadcaster]: Variance: 231589.582582 us
--
[INFO] [1744704820.471171285] [joint_state_broadcaster]: Average update time: 239.791200 us
[INFO] [1744704820.471218683] [joint_state_broadcaster]: Variance: 462334.572003 us
--
[INFO] [1744704823.045886822] [joint_state_broadcaster]: Average update time: 235.594400 us
[INFO] [1744704823.045938966] [joint_state_broadcaster]: Variance: 26580.964489 us
--
[INFO] [1744704825.625277357] [joint_state_broadcaster]: Average update time: 235.583400 us
[INFO] [1744704825.625330096] [joint_state_broadcaster]: Variance: 231611.694044 us
--
[INFO] [1744704828.254401907] [joint_state_broadcaster]: Average update time: 241.029100 us
[INFO] [1744704828.254448233] [joint_state_broadcaster]: Variance: 462391.610853 us
--
[INFO] [1744704830.802185520] [joint_state_broadcaster]: Average update time: 232.373100 us
[INFO] [1744704830.802232534] [joint_state_broadcaster]: Variance: 811.116296 us
--
[INFO] [1744704833.448850699] [joint_state_broadcaster]: Average update time: 242.778300 us
[INFO] [1744704833.448903136] [joint_state_broadcaster]: Variance: 462345.285149 us
--
[INFO] [1744704836.060410410] [joint_state_broadcaster]: Average update time: 238.798000 us
[INFO] [1744704836.060460679] [joint_state_broadcaster]: Variance: 231659.275996 us
```

**Comment by jordan-palacios** [comment]
Performance after commits 109e77b and 68f8006.

```
[INFO] [1744720458.387674748] [joint_state_broadcaster]: Average update time: 104.401400 us
[INFO] [1744720458.387729533] [joint_state_broadcaster]: Variance: 666.211078 us
--
[INFO] [1744720459.388269041] [joint_state_broadcaster]: Average update time: 97.554600 us
[INFO] [1744720459.388316935] [joint_state_broadcaster]: Variance: 635.869019 us
--
[INFO] [1744720460.470225962] [joint_state_broadcaster]: Average update time: 105.671000 us
[INFO] [1744720460.470271104] [joint_state_broadcaster]: Variance: 130682.988159 us
--
[INFO] [1744720461.487041781] [joint_state_broadcaster]: Average update time: 99.057700 us
[INFO] [1744720461.487087239] [joint_state_broadcaster]: Variance: 649.182571 us
--
[INFO] [1744720462.514010777] [joint_state_broadcaster]: Average update time: 100.094300 us
[INFO] [1744720462.514054778] [joint_state_broadcaster]: Variance: 7139.876608 us
--
[INFO] [1744720463.565642664] [joint_state_broadcaster]: Average update time: 103.012900 us
[INFO] [1744720463.565686023] [joint_state_broadcaster]: Variance: 687.822734 us
--
[INFO] [1744720464.608627630] [joint_state_broadcaster]: Average update time: 101.937700 us
[INFO] [1744720464.608671023] [joint_state_broadcaster]: Variance: 676.558219 us
--
[INFO] [1744720465.684515309] [joint_state_broadcaster]: Average update time: 105.071300 us
[INFO] [1744720465.684570711] [joint_state_broadcaster]: Variance: 161106.798816 us
--
[INFO] [1744720466.708715393] [joint_state_broadcaster]: Average update time: 99.883600 us
[INFO] [1744720466.708758278] [joint_state_broadcaster]: Variance: 667.002251 us
--
[INFO] [1744720467.759692043] [joint_state_broadcaster]: Average update time: 102.654400 us
[INFO] [1744720467.759743639] [joint_state_broadcaster]: Variance: 668.791361 us
```

**Comment by jordan-palacios** [comment]
Performance after latest commits.

```
[INFO] [1744723251.403841025] [joint_state_broadcaster]: Average update time: 93.328200 us
[INFO] [1744723251.403888287] [joint_state_broadcaster]: Variance: 653.289085 us
--
[INFO] [1744723252.289001397] [joint_state_broadcaster]: Average update time: 85.812700 us
[INFO] [1744723252.289046780] [joint_state_broadcaster]: Variance: 545.987019 us
--
[INFO] [1744723253.209827955] [joint_state_broadcaster]: Average update time: 89.418700 us
[INFO] [1744723253.209875617] [joint_state_broadcaster]: Variance: 606.806190 us
--
[INFO] [1744723254.181901435] [joint_state_broadcaster]: Average update time: 94.719100 us
[INFO] [1744723254.181943388] [joint_state_broadcaster]: Variance: 7150.674195 us
--
[INFO] [1744723255.104042700] [joint_state_broadcaster]: Average update time: 89.827100 us
[INFO] [1744723255.104083336] [joint_state_broadcaster]: Variance: 571.054806 us
--
[INFO] [1744723256.046535039] [joint_state_broadcaster]: Average update time: 91.721900 us
[INFO] [1744723256.046578421] [joint_state_broadcaster]: Variance: 58434.660360 us
--
[INFO] [1744723256.981178385] [joint_state_broadcaster]: Average update time: 91.173800 us
[INFO] [1744723256.981223162] [joint_state_broadcaster]: Variance: 194645.084994 us
--
[INFO] [1744723257.930289307] [joint_state_broadcaster]: Average update time: 92.436200 us
[INFO] [1744723257.930340540] [joint_state_broadcaster]: Variance: 161048.665130 us
--
[INFO] [1744723258.845409847] [joint_state_broadcaster]: Average update time: 89.336100 us
[INFO] [1744723258.845449674] [joint_state_broadcaster]: Variance: 583.038737 us
--
[INFO] [1744723259.815155478] [joint_state_broadcaster]: Average update time: 94.531100 us
[INFO] [1744723259.815198062] [joint_state_broadcaster]: Variance: 161081.755233 us
```

**Comment by bmagyar** [comment]
Thank you for all the effort on this, the performance improvement is already superb but I'm also very happy about that massive reduction in *variance*.

**Comment by jordan-palacios** [comment]
> Thank you for all the effort on this, the performance improvement is already superb but I'm also very happy about that massive reduction in _variance_.

My pleasure man. This is actually a nice break from the routine. :D

Performance after latest commits.

```
[INFO] [1744725296.145316901] [joint_state_broadcaster]: Average update time: 79.106100 us
[INFO] [1744725296.145362394] [joint_state_broadcaster]: Variance: 3.793643 us
--
[INFO] [1744725296.912327763] [joint_state_broadcaster]: Average update time: 74.606500 us
[INFO] [1744725296.912380387] [joint_state_broadcaster]: Variance: 2.370858 us
--
[INFO] [1744725297.710840156] [joint_state_broadcaster]: Average update time: 77.324300 us
[INFO] [1744725297.710892160] [joint_state_broadcaster]: Variance: 2.856730 us
--
[INFO] [1744725298.512992702] [joint_state_broadcaster]: Average update time: 77.753300 us
[INFO] [1744725298.513033306] [joint_state_broadcaster]: Variance: 2.283639 us
--
[INFO] [1744725299.320802269] [joint_state_broadcaster]: Average update time: 78.241700 us
[INFO] [1744725299.320844377] [joint_state_broadcaster]: Variance: 3.354681 us
--
[INFO] [1744725300.194178435] [joint_state_broadcaster]: Average update time: 84.872500 us
[INFO] [1744725300.194222263] [joint_state_broadcaster]: Variance: 160107.591044 us
--
[INFO] [1744725300.996058420] [joint_state_broadcaster]: Average update time: 77.732800 us
[INFO] [1744725300.996096360] [joint_state_broadcaster]: Variance: 2.465004 us
--
[INFO] [1744725301.825376099] [joint_state_broadcaster]: Average update time: 80.907000 us
[INFO] [1744725301.825426253] [joint_state_broadcaster]: Variance: 102490.028351 us
--
[INFO] [1744725302.643891628] [joint_state_broadcaster]: Average update time: 79.371900 us
[INFO] [1744725302.643944670] [joint_state_broadcaster]: Variance: 6432.001190 us
--
[INFO] [1744725303.452169592] [joint_state_broadcaster]: Average update time: 78.211600 us
[INFO] [1744725303.452222442] [joint_state_broadcaster]: Variance: 2.680825 us
```

File: joint_state_broadcaster/src/joint_state_broadcaster.cpp [hunk 1]
```diff
@@ -346,18 +403,19 @@ double get_value(
...
+    /// make sense to try to get the latest value on every iteration?
+    const auto & opt = state_interfaces_[i].get_optional();
+    if (opt.has_value())
     {
-      interface_name = map_interface_to_joint_state_[interface_name];
+      *mapped_values_[i] = opt.value();
+
+      /// @warning calling this for each interface is too costly, even if it ends up not logging
+      // RCLCPP_DEBUG(get_node()->get_logger(), "%s: %f\n", state_interfaces_[i].get_name().c_str(),
+      // opt.value());
```
Comment (saikishor) [inline joint_state_broadcaster/src/joint_state_broadcaster.cpp:417]:
```suggestion
```

File: joint_state_broadcaster/src/joint_state_broadcaster.cpp [hunk 2]
```diff
@@ -346,18 +403,19 @@ double get_value(
...
   const rclcpp::Time & time, const rclcpp::Duration & /*period*/)
 {
-  for (const auto & state_interface : state_interfaces_)
+  for (auto i = 0u; i < state_interfaces_.size(); ++i)
   {
-    std::string interface_name = state_interface.get_interface_name();
-    if (map_interface_to_joint_state_.count(interface_name) > 0)
+    /// @note should we limit the number of retries here? does it even
+    /// make sense to try to get the latest value on every iteration?
+    const auto & opt = state_interfaces_[i].get_optional();
```
Comment (saikishor) [inline joint_state_broadcaster/src/joint_state_broadcaster.cpp:410]:
```suggestion
    const auto & opt = state_interfaces_[i].get_optional(0);
```
Can you set the number of retries to zero (or) one?

**Review by saikishor — CHANGES_REQUESTED** [review]
The changes look really good to me. Thank you for the initiative :)

Just minor things

**Review by christophfroehlich — APPROVED** [review]
Looks great, and also tested in my setup

File: joint_state_broadcaster/src/joint_state_broadcaster.cpp (hunk 1 above)
Comment (jordan-palacios) [reply joint_state_broadcaster/src/joint_state_broadcaster.cpp]: Removed.

File: joint_state_broadcaster/src/joint_state_broadcaster.cpp (hunk 2 above)
Comment (jordan-palacios) [reply joint_state_broadcaster/src/joint_state_broadcaster.cpp]: Done,

**Review by saikishor — APPROVED** [review]
Great job. Thank you so much!

LGTM

**Review by christophfroehlich — APPROVED** [review]
