### PR TITLE
[JTC] Tolerance tests + Hold on time violation

### LINKED ISSUE #407: [JTC] Add new test to ensure that controller goes into position holding when tolerances are violated
[...] Would it be possible to write a small test for this behavior? We would then feel better in the future to know that behavior is not broken (again).

_Originally posted by @destogl in https://github.com/ros-controls/ros2_controllers/pull/368#pullrequestreview-1019716551_

### PR DESCRIPTION
**Pull request by christophfroehlich**
I realized that if using the topic interface: The current trajectory will never be stopped if the goal isn't reached within time. 

New tests fix #407 but need
- [x] #558 to succeed, because `set_hold_position` does not set hold position now

### CODE REVIEW

**Comment by christophfroehlich** [comment]
CI fails because of flaky JTC tests, not related to this PR

File: joint_trajectory_controller/src/joint_trajectory_controller.cpp [hunk 1]
```diff
@@ -362,19 +362,28 @@ controller_interface::return_type JointTrajectoryController::update(
...
         RCLCPP_ERROR(get_node()->get_logger(), "Holding position due to state tolerance violation");
 
         traj_msg_external_point_ptr_.reset();
         traj_msg_external_point_ptr_.initRT(set_hold_position());
       }
+      else if (
+        !before_last_point && !within_goal_time && *(rt_has_pending_goal_.readFromRT()) == false)
+      {
+        RCLCPP_ERROR(
+          get_node()->get_logger(), "Holding position due goal_time_tolerance exceeding");
```
Comment (bmagyar) [inline joint_trajectory_controller/src/joint_trajectory_controller.cpp:379]:
```suggestion
          get_node()->get_logger(), "Exceeded goal_time_tolerance: holding position...");
```

**Review by bmagyar — APPROVED** [review]
