### PR TITLE
Check robot description validity in AdmittanceController

### LINKED ISSUE #713: admittance_controller should fail with invalid robot_description
## Background
As per #711 there's a disabled test now for admittance_controller validating the above.
Re-enable the test & fix the behaviour ;)

https://github.com/ros-controls/ros2_controllers/blob/master/admittance_controller/test/test_admittance_controller.cpp#L70

## Instructions
Hi, this is a `good-first-issue` issue. This means we've worked to make it more legible to people who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

We're interested in helping you take the first step, and can answer questions and help you out along the way. Note that we're especially interested in contributions from underrepresented groups!

We know that creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this PR for someone new**, and looking through our general [bug](https://github.com/ros-controls/ros2_control/labels/bug) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 🗄️ **Create a local workspace** for making your changes and testing [following these instructions](https://docs.ros.org/en/rolling/Tutorials/Workspace/Creating-A-Workspace.html), for Step 3 use "Download Source Code" section with [these instructions](https://control.ros.org/master/doc/getting_started/getting_started.html#building-from-source).

- [ ] 🍴 **Fork the repository** using the handy button at the top of the repository page and **clone** it into `~/ws_ros2_control/src/ros-controls/ros2_control`, [here is a guide that you can follow](https://guides.github.com/activities/forking/) (You will have to remove or empty the existing `ros2_control` folder before cloning your own fork)

- [ ] **Checkout a new branch** using `git checkout -b <branch_name>`

- [ ] 🤖 **Apply `pre-commit`** auto formatting, by running `pip3 install pre-commit` and running `pre-commit install` in the ros2_control repo.

- [ ] 💾 **Commit and Push** your changes

- [ ] 🔀 **Start a Pull Request** to request to merge your code into `master`. There are two ways that you can start a pull request:
1. If you are not familiar with GitHub or how to create a pull request, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!**

### 🤔❓ Questions?

Don’t hesitate to ask questions or to get help if you feel like you are getting stuck. For example leave a comment below!
Furthermore, you find helpful resources here:
* [ROS2 Control Contribution Guide](https://control.ros.org/master/doc/contributing/contributing.html)
* [ROS2 Tutorials](https://docs.ros.org/en/rolling/Tutorials.html)
* [Robotics Stack Exchange](https://robotics.stackexchange.com)

**Good luck with your first issue!**

### PR DESCRIPTION
**Pull request by caio-freitas**
Fix #713 

- Uncommented test case with "bad_robot" as robot description from test suite in `test_admittance_controller.cpp`.
- Updated the `on_init` on `test_admittance_controller.hpp` to only override the robot description with the one defined in the `ros2_control_test_assets` if not already defined.
- On the initialization of the admittance controller, verified if the robot description is a valid xml, similar to what's done in `ros2_control/hardware_interface/src/component_parser.cpp` ([here](https://github.com/ros-controls/ros2_control/blob/eba8665da4dd656c9a5addab6f0dd19889103668/hardware_interface/src/component_parser.cpp#L968))

### CODE REVIEW

File: admittance_controller/src/admittance_controller.cpp [hunk 1]
```diff
@@ -16,6 +16,7 @@
 
 #include "admittance_controller/admittance_controller.hpp"
 
+#include <tinyxml2.h>
```
Comment (christophfroehlich) [inline admittance_controller/src/admittance_controller.cpp:19]: we'll need to add this as dependency (do we need to link against in the Cmake file?)
https://github.com/ros/urdfdom/blob/973baf479512b0b34951b3d5ebb616c22990d781/package.xml#L20

File: admittance_controller/src/admittance_controller.cpp [hunk 2]
```diff
@@ -92,6 +93,33 @@ controller_interface::CallbackReturn AdmittanceController::on_init()
   reference_admittance_ = last_reference_;
   joint_state_ = last_reference_;
 
+  std::string robot_description = get_node()->get_parameter("robot_description").as_string();
```
Comment (christophfroehlich) [inline admittance_controller/src/admittance_controller.cpp]: I'm not sure about this. The admittance controller doesn't use the `robot_description` parameter, but uses `this->get_robot_description()` from controller_interface_base since #1247. We should use this here as well obviously.
For the tests, you have to set `controller_->robot_description_` to override this.

File: admittance_controller/test/test_admittance_controller.hpp [hunk 3]
```diff
@@ -76,11 +76,17 @@ class TestableAdmittanceController : public admittance_controller::AdmittanceCon
...
-    get_node()->declare_parameter(
-      "robot_description_semantic", rclcpp::ParameterType::PARAMETER_STRING);
-    get_node()->set_parameter({"robot_description", robot_description_});
-    get_node()->set_parameter({"robot_description_semantic", robot_description_semantic_});
+    if (!get_node()->has_parameter("robot_description"))
+    {
+      get_node()->declare_parameter("robot_description", rclcpp::ParameterType::PARAMETER_STRING);
+      get_node()->set_parameter({"robot_description", robot_description_});
+    }
+    if (!get_node()->has_parameter("robot_description_semantic"))
```
Comment (christophfroehlich) [inline admittance_controller/test/test_admittance_controller.hpp]: I think this can be deleted, I don't find any usage of `robot_description_semantic`?

File: admittance_controller/test/test_admittance_controller.hpp
Comment (christophfroehlich) [inline admittance_controller/test/test_admittance_controller.hpp:1]: L393-394 has commented code regarding robot_description, this should also be deleted.

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
Thank you for taking this. I have some doubts if this is tested properly, see the comments

**Comment by christophfroehlich** [comment]
Thinking again, is there really a need to check this inside the controller? The controller manager will not start with a broken urdf, right @saikishor ?

**Review by saikishor — CHANGES_REQUESTED** [review]
I agree with @christophfroehlich that this is not needed as CM provides a valid one. 

Can you explain to us, why did you have a need to do this?

**Comment by christophfroehlich** [comment]
see the linked issue, but this was before we passed the robot description from the cm to the controllers. sorry for not checking that earlier. @caio-freitas would you mind in reverting this and cleanup the tests as by my comments instead?

File: admittance_controller/src/admittance_controller.cpp (hunk 2 above)
Comment (bmagyar) [reply admittance_controller/src/admittance_controller.cpp]: worst case we may have some work left to refactor on this controller to use the URDF we pass to the controller, we shouldn't fetch a param: https://github.com/ros-controls/ros2_control/pull/1088/files

Comment (christophfroehlich) [reply admittance_controller/src/admittance_controller.cpp]: as i've seen we don't parse it as a parameter any more, that's only a remnant in the tests

File: admittance_controller/src/admittance_controller.cpp (hunk 1 above)
Comment (caio-freitas) [reply admittance_controller/src/admittance_controller.cpp:19]: I've added it a dependency on both `CMakeLists.txt` and `package.xml`

File: admittance_controller/test/test_admittance_controller.hpp [hunk 4]
```diff
@@ -76,10 +76,14 @@ class TestableAdmittanceController : public admittance_controller::AdmittanceCon
...
+    if (!get_node()->has_parameter("robot_description"))
+    {
+      get_node()->declare_parameter("robot_description", rclcpp::ParameterType::PARAMETER_STRING);
+      get_node()->set_parameter({"robot_description", robot_description_});
+    }
+
     get_node()->declare_parameter(
       "robot_description_semantic", rclcpp::ParameterType::PARAMETER_STRING);
-    get_node()->set_parameter({"robot_description", robot_description_});
     get_node()->set_parameter({"robot_description_semantic", robot_description_semantic_});
```
Comment (christophfroehlich) [inline admittance_controller/test/test_admittance_controller.hpp]: please also delete robot_description_semantic (and other occurrences if they exist)

File: admittance_controller/test/test_admittance_controller.hpp [hunk 5]
```diff
@@ -76,10 +76,14 @@ class TestableAdmittanceController : public admittance_controller::AdmittanceCon
 public:
   CallbackReturn on_init() override
   {
-    get_node()->declare_parameter("robot_description", rclcpp::ParameterType::PARAMETER_STRING);
+    if (!get_node()->has_parameter("robot_description"))
+    {
+      get_node()->declare_parameter("robot_description", rclcpp::ParameterType::PARAMETER_STRING);
+      get_node()->set_parameter({"robot_description", robot_description_});
```
Comment (christophfroehlich) [inline admittance_controller/test/test_admittance_controller.hpp]: This has no effect, see the failing test

```
2: [ RUN      ] InvalidParameterDuringConfiguration/AdmittanceControllerTestParameterizedInvalidParameters.invalid_parameters/7
2: /workspaces/ros2_rolling_ws/src/ros2_controllers/admittance_controller/test/test_admittance_controller.cpp:73: Failure
2: Expected equality of these values:
2:   SetUpController()
2:     Which is: 1-byte object <00>
2:   controller_interface::return_type::ERROR
2:     Which is: 1-byte object <01>
```

Instead you have to `get_parameter` (to get it from the parameterized test suite) and override `robot_description_` member variable, which will be used for `controller_interface::ControllerInterfaceParams params` in `SetUpControllerCommon`

Comment (caio-freitas) [reply admittance_controller/test/test_admittance_controller.hpp]: It seems like we can't use `get_node()` on the `SetUpControllerCommon()`, should we then take that value from the `options.parameter_overrides()` or is there another way using `get_parameter()` that I'm missing?

Comment (caio-freitas) [reply admittance_controller/test/test_admittance_controller.hpp]: I've set the `controller_->robot_description` to the value passed to the parameter overrides before initializing the controller, since we don't have access to the overrides on `TestableAdmittanceController::on_init()`. Let me know if you agree with the approach.

Comment (christophfroehlich) [reply admittance_controller/test/test_admittance_controller.hpp]: This looks fine. Let's see if CI is happy now.

File: admittance_controller/CMakeLists.txt [hunk 6]
```diff
@@ -23,6 +23,7 @@ set(THIS_PACKAGE_INCLUDE_DEPENDS
   tf2_geometry_msgs
   tf2_kdl
   tf2_ros
+  tinyxml2
```
Comment (christophfroehlich) [inline admittance_controller/CMakeLists.txt]:
```
   --- stderr: admittance_controller
  CMake Error at CMakeLists.txt:33 (find_package):
    By not providing "Findtinyxml2.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "tinyxml2",
    but CMake did not find one.
  
    Could not find a package configuration file provided by "tinyxml2" with any
    of the following names:
  
      tinyxml2Config.cmake
      tinyxml2-config.cmake
  
    Add the installation prefix of "tinyxml2" to CMAKE_PREFIX_PATH or set
    "tinyxml2_DIR" to a directory containing one of the above files.  If
    "tinyxml2" provides a separate development package or SDK, be sure it has
    been installed.
  
  
  ---
```
But it works here
https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/CMakeLists.txt#L16
with the capitalized version

```suggestion
  TinyXML2
```

Comment (christophfroehlich) [reply admittance_controller/CMakeLists.txt]: And please add to target_link_libraries below:

                      ${TinyXML2_LIBRARIES}

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
the compatibility build fails, please review
